name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge changes
        run: git merge upstream/main

      - name: Push changes to origin
        run: git push origin main
